apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metrisv2
  name: metrisv2
  namespace: kcp-system
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: metrisv2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: metrisv2
    spec:
      containers:
      - image: ko://github.com/kyma-incubator/metris/cmd
        imagePullPolicy: Always
        name: metrisv2
        env:
          - name: PUBLIC_CLOUD_SPECS
            valueFrom:
              configMapKeyRef:
                name: public-cloud-specs
                key: providers
        volumeMounts:
          - mountPath: /gardener
            name: gardener-kubeconfig
            readOnly: true
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: gardener-kubeconfig
        secret:
          secretName: gardener-credentials
